stages:
- deploy
- fail
- ok

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get -y -qq install git-core zip gcc zlib1g-dev ca-certificates libxml2-utils python python-pyvorbis python-ogg pyton-pil
  - cd ..
  - rm -rf tools
  - git clone --depth 1 https://gitlab.com/evol/evol-tools.git tools
  - ./tools/gitlab-ci/clientdata.sh
  artifacts:
    paths:
    - public
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - .shared
  only:
  - master
 
ok_job:
  stage: ok
  script:
  - apt-get update
  - apt-get -y -qq install ii psmisc
  - cd ..
  - rm -rf tools
  - git clone --depth 1 https://gitlab.com/evol/evol-tools.git tools
  - ./tools/gitlab-ci/susseccaction.sh
  when: on_success
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - .shared
  dependencies:
  - pages
  only:
  - master

fail_job:
  stage: fail
  script:
  - apt-get update
  - apt-get -y -qq install ii psmisc pastebinit
  - cd ..
  - rm -rf tools
  - git clone --depth 1 https://gitlab.com/evol/evol-tools.git tools
  - ./tools/gitlab-ci/failaction.sh
  when: on_failure
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - .shared
  artifacts:
    paths:
    - .shared/error.log
  dependencies:
  - pages
  only:
  - master
